import com.in6k.aviaTicketDesk.dao.CityDAO;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by employee on 7/28/16.
 */
public class DatabaseInitializer {
    private Statement statement;
    CityDAO cityDAO;


    void prepareDatabase() throws Exception {
        statement = DriverManager.getConnection("jdbc:hsqldb:mem:shop", "user", "852").createStatement();
        prepareTables();
        prepareCities();
        beansSetUp();
    }

    private void prepareTables() throws SQLException {
        statement.executeUpdate(
                "CREATE TABLE cities (" +
                "id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY , " +
                "title VARCHAR(25) );");


    }

    private void beansSetUp() {
        ClassPathXmlApplicationContext applicationContext = new ClassPathXmlApplicationContext(new String[]{"config.xml"});
        cityDAO = (CityDAO) applicationContext.getBean("cityDAO");
    }

    private void prepareCities() throws SQLException {
        statement.executeUpdate("INSERT INTO cities (title) VALUES ('Tripoli');");
        statement.executeUpdate("INSERT INTO cities (title) VALUES ( 'Manacor');");
        statement.executeUpdate("INSERT INTO cities (title) VALUES ( 'Andorra');");
        statement.executeUpdate("INSERT INTO cities (title) VALUES ( 'Bremen');");
        statement.executeUpdate("INSERT INTO cities (title) VALUES ( 'Motala');");
        statement.executeUpdate("INSERT INTO cities (title) VALUES ( 'Elk');");

    }

    void shutDownDatabase() throws SQLException {
        statement.executeUpdate("DROP TABLE cities");
    }
}
